let data_list=[
    {
        "nom_comercial": "ACRAMITE 480 SC ",
        "date_expiration": "2028-12-25",
        "categorie": "Insecticide",
        "matiere_active": "Bifenazate (480 g/L)",
        "cible": "Acariens",
        "dose": "25",
        "dose_par": "cc/hl",
        "dar": "3",
        "LMR_UE_LMR_GB": "0.01",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "Le traitement peut être appliqué 2 fois MAXIMUM, avec 7 Jours d'intervalle."
    },
    {
        "nom_comercial": "AGRIZOLE ",
        "date_expiration": "2028-12-26",
        "categorie": "Fongicide",
        "matiere_active": "Difenoconazole (250 g/L)",
        "cible": "Rouille",
        "dose": "50",
        "dose_par": "cc/hl",
        "dar": "14",
        "LMR_UE_LMR_GB": "1.00",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "ALFABET 250 SC",
        "date_expiration": "2028-12-27",
        "categorie": "Fongicide",
        "matiere_active": "Azoxystrobin (250 g/L)",
        "cible": "Anthracnose",
        "dose": "1",
        "dose_par": "l/ha",
        "dar": "7",
        "LMR_UE_LMR_GB": "3.00",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "ALLIGATOR ",
        "date_expiration": "2028-12-28",
        "categorie": "Insecticide",
        "matiere_active": "Abamectin (aka avermectin) (1,8%)",
        "cible": "Acariens",
        "dose": "50",
        "dose_par": "cc/hl",
        "dar": "7",
        "LMR_UE_LMR_GB": "0.03",
        "nbr_application": "3",
        "reentree": "1",
        "observation": "Appliqué au MAXIMUM 3 fois"
    },
    {
        "nom_comercial": "ALMECTIN",
        "date_expiration": "2028-12-29",
        "categorie": "Insecticide",
        "matiere_active": "Abamectin (aka avermectin) (18 g/L)",
        "cible": "Acariens",
        "dose": "75",
        "dose_par": "cc/hl",
        "dar": "7",
        "LMR_UE_LMR_GB": "0.03",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "ASSAMA 250 SC",
        "date_expiration": "2028-12-30",
        "categorie": "Fongicide",
        "matiere_active": "Azoxystrobin (250 g/L)",
        "cible": "Anthracnose",
        "dose": "1",
        "dose_par": "l/ha",
        "dar": "7",
        "LMR_UE_LMR_GB": "3",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "2 Applications MAXIMUM, avec 14 Jours d'intervalle."
    },
    {
        "nom_comercial": "AZUMO MG",
        "date_expiration": "2028-12-31",
        "categorie": "Fongicide",
        "matiere_active": "Sulphur (80%)",
        "cible": "Oidium",
        "dose": "300",
        "dose_par": "g/ha",
        "dar": "0",
        "LMR_UE_LMR_GB": "-",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "AZUR 250 SC",
        "date_expiration": "2029-01-01",
        "categorie": "Fongicide",
        "matiere_active": "Azoxystrobin (250 g/L)",
        "cible": "Anthracnose",
        "dose": "1",
        "dose_par": "l/ha",
        "dar": "7",
        "LMR_UE_LMR_GB": "3.00",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "2 Applications MAXIMUM, avec 14 Jours d'intervalle."
    },
    {
        "nom_comercial": "BACTOSPEINE DF",
        "date_expiration": "2029-01-02",
        "categorie": "Bio-pesticide",
        "matiere_active": "Bacillus thuringiensis subsp. Kurstaki strain ABTS 351 (32000 IU/mg)",
        "cible": "Noctuelles défoliatrices",
        "dose": "0.5",
        "dose_par": "kg/ha",
        "dar": "0",
        "LMR_UE_LMR_GB": "0.01",
        "nbr_application": "8",
        "reentree": "2",
        "observation": "8 Applications MAXIMUM, avec 7 à 10 Jours d'intervalle."
    },
    {
        "nom_comercial": "BALIZOR",
        "date_expiration": "2029-01-03",
        "categorie": "Fongicide",
        "matiere_active": "Pyraclostrobin (6.7%)+Boscalid (formerly nicobifen) (26.7%)",
        "cible": "Rouille",
        "dose": "125",
        "dose_par": "g/hl",
        "dar": "3",
        "LMR_UE_LMR_GB": "0.60 + 5.00",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "BENEVIA",
        "date_expiration": "2029-01-04",
        "categorie": "Insecticide",
        "matiere_active": "Cyantraniliprole (100 g/L)",
        "cible": "Pucerons",
        "dose": "60",
        "dose_par": "cc/hl",
        "dar": "3",
        "LMR_UE_LMR_GB": "1.50",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "Appliqué au MAXIMUM 2 fois"
    },
    {
        "nom_comercial": "BIOPROTECT",
        "date_expiration": "2029-01-05",
        "categorie": "Insecticide",
        "matiere_active": "Pyrethrins (20 g/L)",
        "cible": "Mouche blanche",
        "dose": "1",
        "dose_par": "l/ha",
        "dar": "1",
        "LMR_UE_LMR_GB": "1.00",
        "nbr_application": "3",
        "reentree": "1",
        "observation": "3 Applications MAXIMUM, avec 7 Jours d'intervalle."
    },
    {
        "nom_comercial": "BUXYZOLE 240SC",
        "date_expiration": "2029-01-06",
        "categorie": "Fongicide",
        "matiere_active": "Azoxystrobin (80 g/L) + Tebuconazole (160g/L)",
        "cible": "Anthracnose",
        "dose": "1",
        "dose_par": "l/ha",
        "dar": "14",
        "LMR_UE_LMR_GB": "3.00 + 2.00",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "Appliqué au MAXIMUM 2 fois"
    },
    {
        "nom_comercial": "CLOSER 240 SC",
        "date_expiration": "2029-01-07",
        "categorie": "Insecticide",
        "matiere_active": "Sulfoxaflor (240 g/L)",
        "cible": "Mouche blanche",
        "dose": "250",
        "dose_par": "cc/ha",
        "dar": "14",
        "LMR_UE_LMR_GB": "0.01",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "Appliqué au MAXIMUM 2 fois"
    },
    {
        "nom_comercial": "CORAGEN",
        "date_expiration": "2029-01-08",
        "categorie": "Insecticide",
        "matiere_active": "Chlorantraniliprole (200 g/L)",
        "cible": "Noctuelles ",
        "dose": "15",
        "dose_par": "cc/hl",
        "dar": "3",
        "LMR_UE_LMR_GB": "0.80",
        "nbr_application": "1",
        "reentree": "1",
        "observation": "Appliqué 1 fois MAXIMUM"
    },
    {
        "nom_comercial": "COSAVET DF",
        "date_expiration": "2029-01-09",
        "categorie": "Fongicide",
        "matiere_active": "Sulphur (80%)",
        "cible": "Oidium",
        "dose": "300",
        "dose_par": "g/hl",
        "dar": "5",
        "LMR_UE_LMR_GB": "-",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "CRONOS",
        "date_expiration": "2029-01-10",
        "categorie": "Fongicide",
        "matiere_active": "Difenoconazole (250 g/L)",
        "cible": "Rouille",
        "dose": "50",
        "dose_par": "cc/hl",
        "dar": "14",
        "LMR_UE_LMR_GB": "1.00",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "2 Applications MAXIMUM, avec 10 à 12 Jours d'intervalle."
    },
    {
        "nom_comercial": "DIFCOR 250 EC",
        "date_expiration": "2029-01-11",
        "categorie": "Fongicide",
        "matiere_active": "Difenoconazole (250 g/L)",
        "cible": "Rouille",
        "dose": "50",
        "dose_par": "cc/hl",
        "dar": "14",
        "LMR_UE_LMR_GB": "1.00",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "2 Applications MAXIMUM, avec 10 à 12 Jours d'intervalle."
    },
    {
        "nom_comercial": "DIFESTAR",
        "date_expiration": "2029-01-12",
        "categorie": "Fongicide",
        "matiere_active": "Difenoconazole (250 g/L)",
        "cible": "Rouille",
        "dose": "50",
        "dose_par": "cc/hl",
        "dar": "14",
        "LMR_UE_LMR_GB": "1.00",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "ECORTILA",
        "date_expiration": "2029-01-13",
        "categorie": "Acaricide",
        "matiere_active": "Hexythiazox (50%)",
        "cible": "Acaricide",
        "dose": "100",
        "dose_par": "g/hl",
        "dar": "15",
        "LMR_UE_LMR_GB": "0.01",
        "nbr_application": "1",
        "reentree": "1",
        "observation": "Appliqué 1 fois MAXIMUM"
    },
    {
        "nom_comercial": "EXIREL TM  (mouche +mineuse)",
        "date_expiration": "2029-01-14",
        "categorie": "Insecticide",
        "matiere_active": "Cyantraniliprole (100 g/L)",
        "cible": "Mouche blanche, Mouche mineuse.",
        "dose": "60",
        "dose_par": "cc/hl",
        "dar": "3",
        "LMR_UE_LMR_GB": "1.50",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "Appliqué au MAXIMUM 2 fois"
    },
    {
        "nom_comercial": "EXIREL TM  (thrips)",
        "date_expiration": "2029-01-15",
        "categorie": "Insecticide",
        "matiere_active": "Cyantraniliprole (100 g/L)",
        "cible": " Thrips",
        "dose": "75",
        "dose_par": "cc/hl",
        "dar": "3",
        "LMR_UE_LMR_GB": "1.50",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "Appliqué au MAXIMUM 2 fois"
    },
    {
        "nom_comercial": "EZOTHIAZOX",
        "date_expiration": "2029-01-16",
        "categorie": "Acaricide",
        "matiere_active": "Hexythiazox (50%)",
        "cible": "Acariens",
        "dose": "100",
        "dose_par": "g/hl",
        "dar": "15",
        "LMR_UE_LMR_GB": "0.01",
        "nbr_application": "1",
        "reentree": "1",
        "observation": "Appliqué 1 fois MAXIMUM"
    },
    {
        "nom_comercial": "FAGUS",
        "date_expiration": "2029-01-17",
        "categorie": "Fongicide",
        "matiere_active": "Difenoconazole (25%)",
        "cible": "Rouille",
        "dose": "50",
        "dose_par": "cc/hl",
        "dar": "14",
        "LMR_UE_LMR_GB": "1.00",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "2 Applications MAXIMUM, avec 10 à 12 Jours d'intervalle."
    },
    {
        "nom_comercial": "FLINT 50 WG",
        "date_expiration": "2029-01-18",
        "categorie": "Fongicide",
        "matiere_active": "Trifloxystrobin (50%)",
        "cible": "Oidium",
        "dose": "20",
        "dose_par": "g/hl",
        "dar": "3",
        "LMR_UE_LMR_GB": "0.80",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "GARDNER",
        "date_expiration": "2029-01-19",
        "categorie": "Fongicide",
        "matiere_active": "Difenoconazole (250 g/L)",
        "cible": "Rouille",
        "dose": "50",
        "dose_par": "cc/hl",
        "dar": "14",
        "LMR_UE_LMR_GB": "1.00",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "GLADIATOR",
        "date_expiration": "2029-01-20",
        "categorie": "Insecticide",
        "matiere_active": "Spinosad (480 g/L)",
        "cible": "Thrips",
        "dose": "200",
        "dose_par": "cc/ha",
        "dar": "3",
        "LMR_UE_LMR_GB": "0.30",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "2 Applications MAXIMUM, avec 10 Jours d'intervalle."
    },
    {
        "nom_comercial": "GLOBAMEC",
        "date_expiration": "2029-01-21",
        "categorie": "Insecticide",
        "matiere_active": "Abamectin (aka avermectin) 18 g/L",
        "cible": "Acariens",
        "dose": "50",
        "dose_par": "cc/hl",
        "dar": "7",
        "LMR_UE_LMR_GB": "0.03",
        "nbr_application": "3",
        "reentree": "1",
        "observation": "Appliqué au MAXIMUM 3 fois"
    },
    {
        "nom_comercial": "GREENTIMEC 18 ec",
        "date_expiration": "2029-01-22",
        "categorie": "Insecticide",
        "matiere_active": "Abamectin (aka avermectin) 18 g/L",
        "cible": "Acariens",
        "dose": "50",
        "dose_par": "cc/hl",
        "dar": "7",
        "LMR_UE_LMR_GB": "0.03",
        "nbr_application": "3",
        "reentree": "1",
        "observation": "3 Applications MAXIMUM, avec 7 Jours d'intervalle."
    },
    {
        "nom_comercial": "HEXY STAR",
        "date_expiration": "2029-01-23",
        "categorie": "Acaricide",
        "matiere_active": "Hexythiazox (50%)",
        "cible": "Acariens",
        "dose": "100",
        "dose_par": "g/hl",
        "dar": "15",
        "LMR_UE_LMR_GB": "0.01",
        "nbr_application": "1",
        "reentree": "1",
        "observation": "Appliqué 1 fois MAXIMUM"
    },
    {
        "nom_comercial": "JACKPOT 50 G/L EC",
        "date_expiration": "2029-01-24",
        "categorie": "Insecticide",
        "matiere_active": "Lambda-Cyhalothrin (50 g/L)",
        "cible": "Pucerons",
        "dose": "25",
        "dose_par": "cc/hl",
        "dar": "7",
        "LMR_UE_LMR_GB": "0.40",
        "nbr_application": "3",
        "reentree": "1",
        "observation": "Appliqué 3 fois MAXIMUM"
    },
    {
        "nom_comercial": "KARATE 5 EC",
        "date_expiration": "2029-01-25",
        "categorie": "Insecticide",
        "matiere_active": "Lambda-Cyhalothrin (50 g/L)",
        "cible": "Pucerons",
        "dose": "25",
        "dose_par": "cc/hl",
        "dar": "7",
        "LMR_UE_LMR_GB": "0.40",
        "nbr_application": "3",
        "reentree": "1",
        "observation": "Appliqué 3 fois MAXIMUM"
    },
    {
        "nom_comercial": "KARIS 10 CS",
        "date_expiration": "2029-01-26",
        "categorie": "Insecticide",
        "matiere_active": "Lambda-Cyhalothrin (10 %)",
        "cible": "Noctuelle",
        "dose": "75",
        "dose_par": "cc/ha",
        "dar": "7",
        "LMR_UE_LMR_GB": "0.40",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "2 Applications MAXIMUM, avec 14 Jours d'intervalle."
    },
    {
        "nom_comercial": "KING 250 EW",
        "date_expiration": "2029-01-27",
        "categorie": "Fongicide",
        "matiere_active": "Tebuconazole (250 g/L)",
        "cible": "Rouille",
        "dose": "40",
        "dose_par": "cc/hl",
        "dar": "14",
        "LMR_UE_LMR_GB": "2.00",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "KOLTHIOR",
        "date_expiration": "2029-01-28",
        "categorie": "Fongicide",
        "matiere_active": "Sulphur (80%)",
        "cible": "Oidium",
        "dose": "300",
        "dose_par": "g/hl",
        "dar": "5",
        "LMR_UE_LMR_GB": "-",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "KUMULUS DF",
        "date_expiration": "2029-01-29",
        "categorie": "Fongicide",
        "matiere_active": "Sulphur (80%)",
        "cible": "Oidium",
        "dose": "300",
        "dose_par": "g/hl",
        "dar": "0",
        "LMR_UE_LMR_GB": "-",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "LUNA SENSATION ",
        "date_expiration": "2029-01-30",
        "categorie": "Fongicide",
        "matiere_active": "Fluopygram (250 g/L) + Trifloxystrobin (250 g/L)",
        "cible": "Oidium",
        "dose": "1",
        "dose_par": "l/ha",
        "dar": "7",
        "LMR_UE_LMR_GB": "1.00 + 0.80",
        "nbr_application": "1",
        "reentree": "1",
        "observation": "Appliqué 1 fois MAXIMUM"
    },
    {
        "nom_comercial": "MARCUS",
        "date_expiration": "2029-01-31",
        "categorie": "Fongicide",
        "matiere_active": "Pyrimenthanil (300 g/L)",
        "cible": "Pourriture grise",
        "dose": "250",
        "dose_par": "cc/hl",
        "dar": "14",
        "LMR_UE_LMR_GB": "3.00",
        "nbr_application": "1",
        "reentree": "1",
        "observation": "Appliqué 1 fois MAXIMUM"
    },
    {
        "nom_comercial": "MAVRIK 2F",
        "date_expiration": "2029-02-01",
        "categorie": "Insecticide",
        "matiere_active": "Tau-Fluvalinate (240 g/L) ",
        "cible": "Acariens, Noctuelles défoliatrices, Thrips, Pucerons, Mouche blanche.",
        "dose": "20",
        "dose_par": "cc/hl",
        "dar": "7",
        "LMR_UE_LMR_GB": "0.10",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "MEGACLAIM ",
        "date_expiration": "2029-02-02",
        "categorie": "Insecticide",
        "matiere_active": "Emamectin (5%)",
        "cible": "Noctuelles",
        "dose": "250",
        "dose_par": "g/ha",
        "dar": "3",
        "LMR_UE_LMR_GB": "0.03",
        "nbr_application": "1",
        "reentree": "1",
        "observation": "Appliqué 1 fois MAXIMUM"
    },
    {
        "nom_comercial": "MYTHOS",
        "date_expiration": "2029-02-03",
        "categorie": "Fongicide",
        "matiere_active": "Pyrimenthanil (300 g/L)",
        "cible": "Pourriture grise",
        "dose": "250",
        "dose_par": "g/hl",
        "dar": "14",
        "LMR_UE_LMR_GB": "3.00",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "NEEMIX 4.5",
        "date_expiration": "2029-02-04",
        "categorie": "Insecticide",
        "matiere_active": "Azadirachtine ( Margosa extract) (45 g/L)",
        "cible": "Mouche blanche",
        "dose": "40",
        "dose_par": "cc/hl",
        "dar": "3",
        "LMR_UE_LMR_GB": "1.00",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "2 Applications MAXIMUM, avec 7 Jours d'intervalle."
    },
    {
        "nom_comercial": "NISSORUN",
        "date_expiration": "2029-02-05",
        "categorie": "Acaricide",
        "matiere_active": "Hexythiazox (10%)",
        "cible": "Acariens",
        "dose": "1",
        "dose_par": "kg/ha",
        "dar": "15",
        "LMR_UE_LMR_GB": "0.01",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "OIKOS",
        "date_expiration": "2029-02-06",
        "categorie": "Insecticide",
        "matiere_active": "Azadirachtine ( Margosa extract) (31,95 g/L)",
        "cible": "Mouche Blanche",
        "dose": "30",
        "dose_par": "cc/hl",
        "dar": "3",
        "LMR_UE_LMR_GB": "1.00",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "ORAMI 25 SC",
        "date_expiration": "2029-02-07",
        "categorie": "Fongicide",
        "matiere_active": "Azoxystrobin (250 g/L)",
        "cible": "Anthracnose",
        "dose": "1",
        "dose_par": "l/ha",
        "dar": "7",
        "LMR_UE_LMR_GB": "3.00",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "2 Applications MAXIMUM, avec 14 Jours d'intervalle."
    },
    {
        "nom_comercial": "ORTIVA 25 SC",
        "date_expiration": "2029-02-08",
        "categorie": "Fongicide",
        "matiere_active": "Azoxystrobin (250 g/L)",
        "cible": "Anthracnose",
        "dose": "1",
        "dose_par": "l/ha",
        "dar": "7",
        "LMR_UE_LMR_GB": "3.00",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "2 PC MAX"
    },
    {
        "nom_comercial": "PILARMECTIN ",
        "date_expiration": "2029-02-09",
        "categorie": "Insecticide",
        "matiere_active": "Abamectin (aka avermectin) (1.8%)",
        "cible": "Acariens",
        "dose": "50",
        "dose_par": "cc/hl",
        "dar": "7",
        "LMR_UE_LMR_GB": "0.03",
        "nbr_application": "3",
        "reentree": "1",
        "observation": "Appliqué 3 fois MAXIMUM"
    },
    {
        "nom_comercial": "PIRIMOR 50 DG",
        "date_expiration": "2029-02-10",
        "categorie": "Insecticide",
        "matiere_active": "Pirimicarb (50%)",
        "cible": "Pucerons",
        "dose": "75",
        "dose_par": "g/hl",
        "dar": "7",
        "LMR_UE_LMR_GB": "1.50",
        "nbr_application": "1",
        "reentree": "1",
        "observation": "Appliqué 1 fois MAXIMUM"
    },
    {
        "nom_comercial": "PROCLAIM 05 SG",
        "date_expiration": "2029-02-11",
        "categorie": "Insecticide",
        "matiere_active": "Emamectin (5%)",
        "cible": "Noctuelles défoliatrices",
        "dose": "250",
        "dose_par": "g/hl",
        "dar": "3",
        "LMR_UE_LMR_GB": "0.03",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "PRONIL ",
        "date_expiration": "2029-02-12",
        "categorie": "Fongicide",
        "matiere_active": "Pyrimenthanil (300 g/L)",
        "cible": "Pourriture grise",
        "dose": "250",
        "dose_par": "cc/hl",
        "dar": "14",
        "LMR_UE_LMR_GB": "3.00",
        "nbr_application": "1",
        "reentree": "1",
        "observation": "Appliqué 1 fois MAXIMUM"
    },
    {
        "nom_comercial": "PROUGE 5 SG",
        "date_expiration": "2029-02-13",
        "categorie": "Insecticide",
        "matiere_active": "Emamectin (5%)",
        "cible": "Noctuelle",
        "dose": "250",
        "dose_par": "g/hl",
        "dar": "3",
        "LMR_UE_LMR_GB": "0.03",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "RAMSES ",
        "date_expiration": "2029-02-14",
        "categorie": "Insecticide",
        "matiere_active": "Emamectin (5%)",
        "cible": "Insecticide",
        "dose": "250",
        "dose_par": "g/hl",
        "dar": "3",
        "LMR_UE_LMR_GB": "0.03",
        "nbr_application": "1",
        "reentree": "1",
        "observation": "Appliqué 1 fois MAXIMUM"
    },
    {
        "nom_comercial": "REVOLUTION 05 SG",
        "date_expiration": "2029-02-15",
        "categorie": "Insecticide",
        "matiere_active": "Emamectin (5%)",
        "cible": "Noctuelle",
        "dose": "250",
        "dose_par": "g/hl",
        "dar": "3",
        "LMR_UE_LMR_GB": "0.03",
        "nbr_application": "1",
        "reentree": "1",
        "observation": "Appliqué 1 fois MAXIMUM"
    },
    {
        "nom_comercial": "SAPHYR 250 SC",
        "date_expiration": "2029-02-16",
        "categorie": "Fongicide",
        "matiere_active": "Azoxystrobin (250 g/L)",
        "cible": "Anthracnose",
        "dose": "1",
        "dose_par": "l/ha",
        "dar": "7",
        "LMR_UE_LMR_GB": "3.00",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "2 Applications MAXIMUM"
    },
    {
        "nom_comercial": "SCOOTER 250 EC",
        "date_expiration": "2029-02-17",
        "categorie": "Fongicide",
        "matiere_active": "Difenoconazole (250 g/L)",
        "cible": "Rouille",
        "dose": "50",
        "dose_par": "cc/hl",
        "dar": "14",
        "LMR_UE_LMR_GB": "1.00",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "2 Applications MAXIMUM, avec 10 à 12 Jours d'intervalle."
    },
    {
        "nom_comercial": "SCORE 250 EC",
        "date_expiration": "2029-02-18",
        "categorie": "Fongicide",
        "matiere_active": "Difenoconazole (250 g/L)",
        "cible": "Rouille",
        "dose": "50",
        "dose_par": "cc/hl",
        "dar": "14",
        "LMR_UE_LMR_GB": "1.00",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "SIGNUM WG",
        "date_expiration": "2029-02-19",
        "categorie": "Fongicide",
        "matiere_active": "Pyraclostrobin (6.7%) + Boscalid (formerly nicobifen) (26.7%)",
        "cible": "Rouille",
        "dose": "125",
        "dose_par": "g/hl",
        "dar": "3",
        "LMR_UE_LMR_GB": "0.60 + 5.00",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "SOLVINOVA",
        "date_expiration": "2029-02-20",
        "categorie": "Insecticide",
        "matiere_active": "Abamectin (aka avermectin) (20 g/L)",
        "cible": "Nematodes",
        "dose": "4",
        "dose_par": "l/ha",
        "dar": "0",
        "LMR_UE_LMR_GB": "0.03",
        "nbr_application": "4",
        "reentree": "1",
        "observation": "4 Applications MAXIMUM, avec 30 Jours d'intervalle."
    },
    {
        "nom_comercial": "SWITCH 62.5 WG",
        "date_expiration": "2029-02-21",
        "categorie": "Fongicide",
        "matiere_active": "Cyprodinil (37.5%) + Fludioxonil (25%)",
        "cible": "Pourriture grise",
        "dose": "60",
        "dose_par": "g/hl",
        "dar": "14",
        "LMR_UE_LMR_GB": "2.00 + 1.00",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "2 Applications MAXIMUM, avec 10 Jours d'intervalle."
    },
    {
        "nom_comercial": "TELDOR 50 WG",
        "date_expiration": "2029-02-22",
        "categorie": "Fongicide",
        "matiere_active": "Fenhexamid (500 g/kg)",
        "cible": "Pourriture grise",
        "dose": "75",
        "dose_par": "g/hl",
        "dar": "3",
        "LMR_UE_LMR_GB": "15.00",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "2 Applications MAXIMUM"
    },
    {
        "nom_comercial": "THIOVIT JET ",
        "date_expiration": "2029-02-23",
        "categorie": "Fongicide",
        "matiere_active": "Sulphur (80%)",
        "cible": "Oidium",
        "dose": "300",
        "dose_par": "g/hl",
        "dar": "5",
        "LMR_UE_LMR_GB": "-",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "VAJRA",
        "date_expiration": "2029-02-24",
        "categorie": "Insecticide",
        "matiere_active": "Lambda-Cyhalothrin (50 g/L)",
        "cible": "Pucerons",
        "dose": "25",
        "dose_par": "cc/hl",
        "dar": "7",
        "LMR_UE_LMR_GB": "0.40",
        "nbr_application": "1",
        "reentree": "1",
        "observation": "Appliqué 1 fois MAXIMUM"
    },
    {
        "nom_comercial": "VERIMARK ",
        "date_expiration": "2029-02-25",
        "categorie": "Insecticide",
        "matiere_active": "Cyantraniliprole (200 g/L)",
        "cible": "Pucerons",
        "dose": "375",
        "dose_par": "cc/ha",
        "dar": "3",
        "LMR_UE_LMR_GB": "1.50",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "2 Applications MAXIMUM"
    },
    {
        "nom_comercial": "VERTIGO 018 EC",
        "date_expiration": "2029-02-26",
        "categorie": "Insecticide",
        "matiere_active": "Abamectin (aka avermectin) (18 g/L)",
        "cible": "Acariens",
        "dose": "75",
        "dose_par": "cc/hl",
        "dar": "7",
        "LMR_UE_LMR_GB": "0.03",
        "nbr_application": "-",
        "reentree": "1",
        "observation": "-"
    },
    {
        "nom_comercial": "VERTIMEC",
        "date_expiration": "2029-02-27",
        "categorie": "Insecticide",
        "matiere_active": "Abamectin (aka avermectin) (18 g/L)",
        "cible": "Acariens",
        "dose": "50",
        "dose_par": "cc/hl",
        "dar": "7",
        "LMR_UE_LMR_GB": "0.03",
        "nbr_application": "3",
        "reentree": "1",
        "observation": "3 Applications MAXIMUM"
    },
    {
        "nom_comercial": "WARRIOR 10 CS AVEC TECHNOLOGIE ZÉON",
        "date_expiration": "2029-02-28",
        "categorie": "Insecticide",
        "matiere_active": "Lambda-Cyhalothrin (100 g/L)",
        "cible": "Moths-Noctuelles control",
        "dose": "125",
        "dose_par": "cc/ha",
        "dar": "7",
        "LMR_UE_LMR_GB": "0.40",
        "nbr_application": "1",
        "reentree": "1",
        "observation": "Appliqué 1 fois MAXIMUM"
    },
    {
        "nom_comercial": "ZERAMEC",
        "date_expiration": "2029-03-01",
        "categorie": "Insecticide",
        "matiere_active": "Abamectin (aka avermectin) (18 g/L)",
        "cible": "Acariens",
        "dose": "50",
        "dose_par": "cc/hl",
        "dar": "7",
        "LMR_UE_LMR_GB": "0.03",
        "nbr_application": "3",
        "reentree": "1",
        "observation": "3 Applications MAXIMUM"
    },
    {
        "nom_comercial": "ZOXYBINE 25 SC",
        "date_expiration": "2029-03-02",
        "categorie": "Fongicide",
        "matiere_active": "Azoxystrobin (250 g/L)",
        "cible": "Anthracnose",
        "dose": "1",
        "dose_par": "l/ha",
        "dar": "7",
        "LMR_UE_LMR_GB": "3.00",
        "nbr_application": "2",
        "reentree": "1",
        "observation": "2 Applications MAXIMUM"
    }
];



let list_produits;
        if(localStorage.list_produits!=null) {
                list_produits=JSON.parse(localStorage.list_produits)
        }else{list_produits=[];}


        
if (!localStorage.getItem('script_has_run')) {
    data_list.forEach(val=>{
        list_produits.push(val);
        localStorage.setItem('list_produits',JSON.stringify(list_produits));

    })

    console.log("Running this script for the first and only time.");
          

    localStorage.setItem('script_has_run', 'true');
}
        


